name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Fetch contributions and generate snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: g8rdier  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
