name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Create dist folder
      - name: Create dist folder
        run: mkdir -p dist

      # Generate the snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: g8rdier
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
