name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */3 * * *"  # Every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate SVGs in root directory instead of dist/
      - uses: Platane/snk@v3
        with:
          github_user_name: g8rdier
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .  # Push from root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
